language: clojure

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk7
  - oraclejdk8

lein: lein2

script: lein2 with-profile dev test

branches:
  only:
    - master
    - feature/datomic-to-dev-dependencies
